### ISSUE TITLE
Translator is not expanding mappings when unions of different FHIR resources occur in CQL

### ISSUE THREAD

**Issue by srankins** [cqframework/clinical_quality_language#1126]
The Translator is not expanding mappings when unions of different FHIR resources occur in CQL. Refer to https://github.com/projecttacoma/fqm-execution/issues/191.

**Comment by mgramigna** [comment]
Minimal replication CQL:

``` cql
library UnionTest
 
using QICore version '4.1.1'

include FHIRHelpers version '4.1.000'

context Patient

define "Union of Different Types":
  ([Procedure] union [ServiceRequest]) R
    return {
      performed: R.performed,
      authoredOn: R.authoredOn
    }

```

**Comment by brynrhodes** [comment]
Fixed in 2.7.0

**Comment by mcmcphillips** [comment]
@brynrhodes 
After updating the translator to 2.7, the unintended behavior described in https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1377 is still present.
