### ISSUE TITLE
cql-to-elm-cli crash on quantity '%' unit

### ISSUE THREAD

**Issue by sunshineco** [cqframework/clinical_quality_language#1185]
On `master`, currently at 8a041ba5 _(Fixes for list Unions (#1182), 2023-08-08)_, `cql-to-elm-cli` crashes when translating `CMS122-v11-0-000-QDM-5-6.cql` to ELM:

```
% cql-to-elm-cli --annotations --locators --disable-list-demotion --disable-list-promotion --disable-method-invocation -f JSON --input ./CMS122-v11-0-000-QDM-5-6.cql
TRANSLATE ./CMS122-v11-0-000-QDM-5-6.cql
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
	at org.fhir.ucum.UcumEssenceService.<init>(UcumEssenceService.java:57)
	at org.cqframework.cql.cql2elm.LibraryManager.getDefaultUcumService(LibraryManager.java:118)
	at org.cqframework.cql.cql2elm.LibraryManager.getUcumService(LibraryManager.java:110)
	at org.cqframework.cql.cql2elm.LibraryBuilder.validateUcumUnit(LibraryBuilder.java:1902)
	at org.cqframework.cql.cql2elm.LibraryBuilder.validateUnit(LibraryBuilder.java:1861)
	at org.cqframework.cql.cql2elm.LibraryBuilder.createQuantity(LibraryBuilder.java:1913)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitQuantity(Cql2ElmVisitor.java:1744)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitQuantity(Cql2ElmVisitor.java:36)
	at org.cqframework.cql.gen.cqlParser$QuantityContext.accept(cqlParser.java:10382)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at org.cqframework.cql.gen.cqlBaseVisitor.visitQuantityLiteral(cqlBaseVisitor.java:1098)
	at org.cqframework.cql.gen.cqlParser$QuantityLiteralContext.accept(cqlParser.java:8643)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at org.cqframework.cql.gen.cqlBaseVisitor.visitLiteralTerm(cqlBaseVisitor.java:909)
	at org.cqframework.cql.gen.cqlParser$LiteralTermContext.accept(cqlParser.java:7803)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at org.cqframework.cql.gen.cqlBaseVisitor.visitTermExpressionTerm(cqlBaseVisitor.java:776)
	at org.cqframework.cql.gen.cqlParser$TermExpressionTermContext.accept(cqlParser.java:6129)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at org.cqframework.cql.gen.cqlBaseVisitor.visitTermExpression(cqlBaseVisitor.java:601)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitTermExpression(Cql2ElmVisitor.java:2401)
	at org.cqframework.cql.gen.cqlParser$TermExpressionContext.accept(cqlParser.java:5075)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visit(Cql2ElmVisitor.java:649)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.parseExpression(Cql2ElmVisitor.java:4639)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitInequalityExpression(Cql2ElmVisitor.java:2350)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitInequalityExpression(Cql2ElmVisitor.java:36)
	at org.cqframework.cql.gen.cqlParser$InequalityExpressionContext.accept(cqlParser.java:4993)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visit(Cql2ElmVisitor.java:649)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.internalVisitExpressionDefinition(Cql2ElmVisitor.java:1246)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitExpressionDefinition(Cql2ElmVisitor.java:1264)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitExpressionDefinition(Cql2ElmVisitor.java:36)
	at org.cqframework.cql.gen.cqlParser$ExpressionDefinitionContext.accept(cqlParser.java:2227)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at org.cqframework.cql.gen.cqlBaseVisitor.visitStatement(cqlBaseVisitor.java:216)
	at org.cqframework.cql.gen.cqlParser$StatementContext.accept(cqlParser.java:2157)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visit(Cql2ElmVisitor.java:649)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitLibrary(Cql2ElmVisitor.java:727)
	at org.cqframework.cql.gen.cqlParser$LibraryContext.accept(cqlParser.java:353)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visit(Cql2ElmVisitor.java:649)
	at org.cqframework.cql.cql2elm.CqlCompiler.run(CqlCompiler.java:196)
	at org.cqframework.cql.cql2elm.CqlTranslator.<init>(CqlTranslator.java:69)
	at org.cqframework.cql.cql2elm.CqlTranslator.fromFile(CqlTranslator.java:54)
	at org.cqframework.cql.cql2elm.cli.Main.writeELM(Main.java:70)
	at org.cqframework.cql.cql2elm.cli.Main.main(Main.java:204)
Caused by: java.lang.ClassNotFoundException: org.xmlpull.v1.XmlPullParserException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 48 more
```

Using v2.11.0, _bd64bcd4 (Update version to 2.11.0, 2023-07-14)_, `cql-to-elm-cli` successfully compiles `CMS122-v11-0-000-QDM-5-6.cql`. `git bisect` places the blame for the crash on commit 69a7cd8e _(Follow-up items for 3.0.0-SNAPSHOT (#1178), 2023-07-12)_.

A minimum-reproduction, extracted directly from `CMS122-v11-0-000-QDM-5-6.cql`, is:

```cql
define "Has Most Recent Elevated HbA1c":
  "Most Recent HbA1c".result > 9 '%'
```

Using `master`, 8a041ba5 _(Fixes for list Unions (#1182), 2023-08-08)_, `cql-to-elm-cli` crashes, showing the above stack-trace. Using v2.11.0, `cql-to-elm-cli` correctly diagnoses that `Most Recent HbA1c` cannot be resolved in the minimum-reproduction fragment:

```
Translation failed due to errors:
Error:[2:3, 2:21] Could not resolve identifier Most Recent HbA1c in the current library.
```

**Comment by brynrhodes** [comment]
@sunshineco , we are unable to reproduce this behavior with the latest translator. The error stack looks like a dependency issue that has since been addressed by an update to the UCUM dependency. Are you able to use the latest translator?

**Comment by brynrhodes** [comment]
I take it back, this looks like it's still an issue because the cli project does not declare a runtime dependency on the xpp3, which is required for the UcumService to run (at least some implementation of an XmlPullParser is required, we use Xpp3 for the command-line). Reopening this and submitting a PR to address it

**Comment by sunshineco** [comment]
Thank you for the response. I can confirm that the crash still occurred as of 69e010f2 (Handle overloaded forward function declarations, 2023-10-11), but was fixed by 6e944b69 (Added runtime dependency on XPP3 to the cli, 2023-10-12) which was merged by pull request #1242.
